<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-09-11T11:10:31+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'api_keys' => array(
        'google' => array(
            'maps' => 'AIzaSyA3mmF-00aSEkToa8Bq_l9snXeCKbFxZ5E',
        ),
    ),
);
