<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-09-11T16:34:59+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'locale' => 'en_GB',
    'site' => 'DataDivers',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1473518480,
        'do_page_reindex_check' => false,
        'latest_version' => '5.7.5.8',
        'favicon_fid' => '1',
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
);
